menu:
    About: /
    Blog: /blog/
    Archive: /archives/
    GitHub: https://github.com/liquidpie
    Rss: /atom.xml

favicon: /favicon.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Information
startyear: 2017
