menu:
    About: /
    Lab: /lab/
    Skills: /skills/
    Blog: /blog/
    Archive: /archives/
    Contact: /contact/
    Rss: /atom.xml

favicon: /favicon.png
logo: /logo.png
thumbnail: /thumbnail.jpg

# urls
facebook_url: https://www.facebook.com/vivek223
linkedin_url: https://www.linkedin.com/in/vivek223
twitter_url: https://twitter.com/vivekjaiswal22
github_url: https://github.com/liquidpie
aboutme_url: https://about.me/vjaiswal

# projects
projects:
    musingly:
        name: Musingly
        image: /icons/project-musingly.png
        url: https://musingly.herokuapp.com
    fdg:
        name: Force Graph
        image: /icons/project-fdg.png
        url: https://force-graph.herokuapp.com

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-115550149-1

# Copyright Information
startyear: 2018
