menu:
    About: /
    Lab: /lab/
    Resume: /resume/
    Blog: /blog/
    Archive: /archives/
    Rss: /atom.xml

favicon: /favicon.png
logo: /logo.png
thumbnail: /thumbnail.jpg
icon_facebook: /icon-facebook.png
icon_linkedin: /icon-linkedin.png
icon_twitter: /icon-twitter.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Information
startyear: 2018
